<?php
$subject = 'Afspraak';
$bodyHTML = '';
$bodyHTML .= '<!DOCTYPE html>';
$bodyHTML .= '<html lang="en">';
$bodyHTML .= '  <head>';
$bodyHTML .= '      <meta charset="UTF-8">';
$bodyHTML .= '      <meta name="viewport" content="width=device-width, initial-scale=1.0">';
$bodyHTML .= '      <title>Appointment Details</title>';
$bodyHTML .= '      <style>';
$bodyHTML .= '          body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 0; }';
$bodyHTML .= '          .container { width: 100%; max-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 20px; box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); }';
$bodyHTML .= '          h1 { font-size: 24px; margin-bottom: 20px; }';
$bodyHTML .= '          p { font-size: 16px; line-height: 1.5; }';
$bodyHTML .= '          ul { list-style-type: none; padding: 0; }';
$bodyHTML .= '          li { font-size: 16px; line-height: 1.5; }';
$bodyHTML .= '      </style>';
$bodyHTML .= '  </head>';
$bodyHTML .= '  <body>';
$bodyHTML .= '      <div class="container">';
$bodyHTML .= '          <h1>Appointment Confirmation</h1>';
$bodyHTML .= '          <p>Dear ' . $appointmentName . ' ' . $appointmentLastname . ',</p>';
$bodyHTML .= '          <p>Thank you for scheduling an appointment with us. Here are the details of your appointment:</p>';
$bodyHTML .= $mailContent;
$bodyHTML .= '          <p>If you have any questions or need to reschedule, please contact us at ' . $appointmentPhone . '.</p>';
$bodyHTML .= '          <p>Best regards,<br>Huismansport Team</p>';
$bodyHTML .= '      </div>';
$bodyHTML .= '  </body>';
$bodyHTML .= '</html>';