<?php
$subject = 'Afspraak';

$bodyHTML  = '<html>';
$bodyHTML .= '<body>';
$bodyHTML .= '<table cellpadding="0" cellspacing="0" width="100%" style="font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#666;">';
$bodyHTML .= '  <tr>';
$bodyHTML .= '    <td align="center">';
$bodyHTML .= '      <table cellpadding="0" cellspacing="0" width="750" style="width:750px; font-family:Arial, Helvetica, sans-serif; font-size:13px; color:#575757; text-align:left;">';
$bodyHTML .= '        <tr>';
$bodyHTML .= '          <td colspan="3">&nbsp;</td>';
$bodyHTML .= '        </tr>';
$bodyHTML .= '        <tr>';
$bodyHTML .= '          <td width="25">&nbsp;</td>';
$bodyHTML .= '          <td width="700">';
$bodyHTML .= '            <table cellpadding="0" cellspacing="0" width="100%" style="font-family:Arial, Helvetica, sans-serif; font-size:13px; color:#575757; text-align:left;">';
$bodyHTML .= '              <tr>';
$bodyHTML .= '                <td>';
$bodyHTML .= '                  <h1>Appointment Confirmation</h1>';
$bodyHTML .= '                  <p>Dear ' . $appointmentName . ' ' . $appointmentLastname . ',</p>';
$bodyHTML .= '                  <p>Thank you for scheduling an appointment with us. Here are the details of your appointment:</p>';
$bodyHTML .= $mailContent;
$bodyHTML .= '                  <p>If you have any questions or need to reschedule, please contact us at ' . $appointmentPhone . '.</p>';
$bodyHTML .= '                  <p>Best regards,<br>Huismansport Team</p>';
$bodyHTML .= '                </td>';
$bodyHTML .= '              </tr>';
$bodyHTML .= '            </table>';
$bodyHTML .= '          </td>';
$bodyHTML .= '          <td width="25">&nbsp;</td>';
$bodyHTML .= '        </tr>';
$bodyHTML .= '        <tr>';
$bodyHTML .= '          <td colspan="3">&nbsp;</td>';
$bodyHTML .= '        </tr>';
$bodyHTML .= '        <tr>';
$bodyHTML .= '          <td colspan="3">';
$bodyHTML .= '            <table cellpadding="0" cellspacing="0" width="100%" style="font-family:Arial, Helvetica, sans-serif; font-size:13px; color:#575757; text-align:left; border-top: 1px solid #e4e4e4; padding-top: 10px;">';
$bodyHTML .= '              <tr>';
$bodyHTML .= '                <td width="180">';
$bodyHTML .= '                  <img src="HuismanSport.png" width="180" height="88" alt="Huisman Sport Logo" border="0" />';
$bodyHTML .= '                </td>';
$bodyHTML .= '                <td width="10" style="border-left: 1px solid #e4e4e4;">&nbsp;</td>';
$bodyHTML .= '                <td style="padding-left: 10px; vertical-align: top;">';
$bodyHTML .= '                  <p style="font-size: 12px; color: #666; margin: 0;">Huismansport</p>';
$bodyHTML .= '                  <p style="font-size: 12px; color: #666; margin: 0;">Vierakkerstraat 20, 6851 BE Huissen</p>';
$bodyHTML .= '                  <p style="font-size: 12px; color: #666; margin: 0;">Phone: 026 - 325 07 43</p>';
$bodyHTML .= '                  <p style="font-size: 12px; color: #666; margin: 0;">Email: info@huismansport.com</p>';
$bodyHTML .= '                </td>';
$bodyHTML .= '              </tr>';
$bodyHTML .= '            </table>';
$bodyHTML .= '          </td>';
$bodyHTML .= '        </tr>';
$bodyHTML .= '      </table>';
$bodyHTML .= '    </td>';
$bodyHTML .= '  </tr>';
$bodyHTML .= '</table>';
$bodyHTML .= '</body>';
$bodyHTML .= '</html>';
?>
